/**
 * Common weapon components (attachments) for GTA V weapons
 * These are component hashes that can be added to weapons
 */

export interface WeaponComponent {
    name: string;
    hash: number;
    weaponHashes: string[]; // Weapons that can use this component
}

export const WEAPON_COMPONENTS: WeaponComponent[] = [
    { name: 'Base Model', hash: 0xF3462F33, weaponHashes: ['weapon_knuckleduster'] },
    { name: 'The Pimp', hash: 0xC613F685, weaponHashes: ['weapon_knuckleduster'] },
    { name: 'The Ballas', hash: 0xEED9FD63, weaponHashes: ['weapon_knuckleduster'] },
    { name: 'The Hustler', hash: 0x50910C31, weaponHashes: ['weapon_knuckleduster'] },
    { name: 'The Rock', hash: 0x9761D9DC, weaponHashes: ['weapon_knuckleduster'] },
    { name: 'The Hater', hash: 0x7DECFE30, weaponHashes: ['weapon_knuckleduster'] },
    { name: 'The Lover', hash: 0x3F4E8AA6, weaponHashes: ['weapon_knuckleduster'] },
    { name: 'The Player', hash: 0x8B808BB, weaponHashes: ['weapon_knuckleduster'] },
    { name: 'The King', hash: 0xE28BABEF, weaponHashes: ['weapon_knuckleduster'] },
    { name: 'The Vagos', hash: 0x7AF3F785, weaponHashes: ['weapon_knuckleduster'] },
    { name: 'Default Handle', hash: 0x9137A500, weaponHashes: ['weapon_switchblade'] },
    { name: 'VIP Variant', hash: 0x5B3E7DB6, weaponHashes: ['weapon_switchblade'] },
    { name: 'Bodyguard Variant', hash: 0xE7939662, weaponHashes: ['weapon_switchblade'] },
    { name: 'Default Clip', hash: 0xFED0FD71, weaponHashes: ['weapon_pistol'] },
    { name: 'Extended Clip', hash: 0xED265A1C, weaponHashes: ['weapon_pistol'] },
    { name: 'Flashlight', hash: 0x359B7AAE, weaponHashes: ['weapon_pistol', 'weapon_combatpistol', 'weapon_appistol', 'weapon_pistol50', 'weapon_heavypistol', 'weapon_revolver_mk2', 'weapon_microsmg'] },
    { name: 'Suppressor', hash: 0x65EA7EBB, weaponHashes: ['weapon_pistol', 'weapon_snspistol_mk2', 'weapon_pistol_mk2'] },
    { name: 'Yusuf Amir Luxury Finish', hash: 0xD7391086, weaponHashes: ['weapon_pistol'] },
    { name: 'Default Clip', hash: 0x721B079, weaponHashes: ['weapon_combatpistol'] },
    { name: 'Extended Clip', hash: 0xD67B4F2D, weaponHashes: ['weapon_combatpistol'] },
    { name: 'Suppressor', hash: 0xC304849A, weaponHashes: ['weapon_combatpistol', 'weapon_appistol', 'weapon_heavypistol', 'weapon_vintagepistol', 'weapon_smg', 'weapon_machinepistol'] },
    { name: 'Yusuf Amir Luxury Finish', hash: 0xC6654D72, weaponHashes: ['weapon_combatpistol'] },
    { name: 'Default Clip', hash: 0x31C4B22A, weaponHashes: ['weapon_appistol'] },
    { name: 'Extended Clip', hash: 0x249A17D5, weaponHashes: ['weapon_appistol'] },
    { name: 'Gilded Gun Metal Finish', hash: 0x9B76C72C, weaponHashes: ['weapon_appistol'] },
    { name: 'Default Clip', hash: 0x2297BE19, weaponHashes: ['weapon_pistol50'] },
    { name: 'Extended Clip', hash: 0xD9D3AC92, weaponHashes: ['weapon_pistol50'] },
    { name: 'Suppressor', hash: 0xA73D4664, weaponHashes: ['weapon_pistol50', 'weapon_microsmg', 'weapon_assaultsmg', 'weapon_bullpupshotgun', 'weapon_assaultrifle', 'weapon_specialcarbine', 'weapon_specialcarbine_mk2', 'weapon_assaultrifle_mk2', 'weapon_sniperrifle', 'weapon_heavyshotgun'] },
    { name: 'Platinum Pearl Deluxe Finish', hash: 0x77B8AB2F, weaponHashes: ['weapon_pistol50'] },
    { name: 'VIP Variant', hash: 0x16EE3040, weaponHashes: ['weapon_revolver'] },
    { name: 'Bodyguard Variant', hash: 0x9493B80D, weaponHashes: ['weapon_revolver'] },
    { name: 'Default Clip', hash: 0xE9867CE3, weaponHashes: ['weapon_revolver'] },
    { name: 'Default Clip', hash: 0xF8802ED9, weaponHashes: ['weapon_snspistol'] },
    { name: 'Extended Clip', hash: 0x7B0033B3, weaponHashes: ['weapon_snspistol'] },
    { name: 'Etched Wood Grip Finish', hash: 0x8033ECAF, weaponHashes: ['weapon_snspistol'] },
    { name: 'Default Clip', hash: 0xD4A969A, weaponHashes: ['weapon_heavypistol'] },
    { name: 'Extended Clip', hash: 0x64F9C62B, weaponHashes: ['weapon_heavypistol'] },
    { name: 'Etched Wood Grip Finish', hash: 0x7A6A7B7B, weaponHashes: ['weapon_heavypistol'] },
    { name: 'Default Rounds', hash: 0xBA23D8BE, weaponHashes: ['weapon_revolver_mk2'] },
    { name: 'Tracer Rounds', hash: 0xC6D8E476, weaponHashes: ['weapon_revolver_mk2'] },
    { name: 'Incendiary Rounds', hash: 0xEFBF25, weaponHashes: ['weapon_revolver_mk2'] },
    { name: 'Hollow Point Rounds', hash: 0x10F42E8F, weaponHashes: ['weapon_revolver_mk2'] },
    { name: 'Full Metal Jacket Rounds', hash: 0xDC8BA3F, weaponHashes: ['weapon_revolver_mk2'] },
    { name: 'Holographic Sight', hash: 0x420FD713, weaponHashes: ['weapon_revolver_mk2', 'weapon_pumpshotgun_mk2', 'weapon_bullpuprifle_mk2', 'weapon_specialcarbine_mk2', 'weapon_assaultrifle_mk2', 'weapon_carbinerifle_mk2', 'weapon_combatmg_mk2', 'weapon_marksmanrifle_mk2'] },
    { name: 'Small Scope', hash: 0x49B2945, weaponHashes: ['weapon_revolver_mk2', 'weapon_pumpshotgun_mk2', 'weapon_specialcarbine_mk2', 'weapon_assaultrifle_mk2', 'weapon_carbinerifle_mk2'] },
    { name: 'Compensator', hash: 0x27077CCB, weaponHashes: ['weapon_revolver_mk2'] },
    { name: 'Digital Camo', hash: 0xC03FED9F, weaponHashes: ['weapon_revolver_mk2'] },
    { name: 'Brushstroke Camo', hash: 0xB5DE24, weaponHashes: ['weapon_revolver_mk2'] },
    { name: 'Woodland Camo', hash: 0xA7FF1B8, weaponHashes: ['weapon_revolver_mk2'] },
    { name: 'Skull', hash: 0xF2E24289, weaponHashes: ['weapon_revolver_mk2'] },
    { name: 'Sessanta Nove', hash: 0x11317F27, weaponHashes: ['weapon_revolver_mk2'] },
    { name: 'Perseus', hash: 0x17C30C42, weaponHashes: ['weapon_revolver_mk2'] },
    { name: 'Leopard', hash: 0x257927AE, weaponHashes: ['weapon_revolver_mk2'] },
    { name: 'Zebra', hash: 0x37304B1C, weaponHashes: ['weapon_revolver_mk2'] },
    { name: 'Geometric', hash: 0x48DAEE71, weaponHashes: ['weapon_revolver_mk2'] },
    { name: 'Boom!', hash: 0x20ED9B5B, weaponHashes: ['weapon_revolver_mk2'] },
    { name: 'Patriotic', hash: 0xD951E867, weaponHashes: ['weapon_revolver_mk2'] },
    { name: 'Default Clip', hash: 0x1466CE6, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Extended Clip', hash: 0xCE8C0772, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Tracer Rounds', hash: 0x902DA26E, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Incendiary Rounds', hash: 0xE6AD5F79, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Hollow Point Rounds', hash: 0x8D107402, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Full Metal Jacket Rounds', hash: 0xC111EB26, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Flashlight', hash: 0x4A4965F3, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Mounted Scope', hash: 0x47DE9258, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Compensator', hash: 0xAA8283BF, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Digital Camo', hash: 0xF7BEEDD, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Brushstroke Camo', hash: 0x8A612EF6, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Woodland Camo', hash: 0x76FA8829, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Skull', hash: 0xA93C6CAC, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Sessanta Nove', hash: 0x9C905354, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Perseus', hash: 0x4DFA3621, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Leopard', hash: 0x42E91FFF, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Zebra', hash: 0x54A8437D, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Geometric', hash: 0x68C2746, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Boom!', hash: 0x2366E467, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Boom!', hash: 0x441882E6, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Digital Camo', hash: 0xE7EE68EA, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Brushstroke Camo', hash: 0x29366D21, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Woodland Camo', hash: 0x3ADE514B, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Skull', hash: 0xE64513E9, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Sessanta Nove', hash: 0xCD7AEB9A, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Perseus', hash: 0xFA7B27A6, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Leopard', hash: 0xE285CA9A, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Zebra', hash: 0x2B904B19, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Geometric', hash: 0x22C24F9C, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Boom!', hash: 0x8D0D5ECD, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Patriotic', hash: 0x1F07150A, weaponHashes: ['weapon_snspistol_mk2'] },
    { name: 'Default Clip', hash: 0x94F42D62, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Extended Clip', hash: 0x5ED6C128, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Tracer Rounds', hash: 0x25CAAEAF, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Incendiary Rounds', hash: 0x2BBD7A3A, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Hollow Point Rounds', hash: 0x85FEA109, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Full Metal Jacket Rounds', hash: 0x4F37DF2A, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Mounted Scope', hash: 0x8ED4BB70, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Flashlight', hash: 0x43FD595B, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Compensator', hash: 0x21E34793, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Digital Camo', hash: 0x5C6C749C, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Brushstroke Camo', hash: 0x15F7A390, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Woodland Camo', hash: 0x968E24DB, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Skull', hash: 0x17BFA99, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Sessanta Nove', hash: 0xF2685C72, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Perseus', hash: 0xDD2231E6, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Leopard', hash: 0xBB43EE76, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Zebra', hash: 0x4D901310, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Geometric', hash: 0x5F31B653, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Boom!', hash: 0x697E19A0, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Patriotic', hash: 0x930CB951, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Digital Camo', hash: 0xB4FC92B0, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Digital Camo', hash: 0x1A1F1260, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Digital Camo', hash: 0xE4E00B70, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Digital Camo', hash: 0x2C298B2B, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Digital Camo', hash: 0xDFB79725, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Digital Camo', hash: 0x6BD7228C, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Digital Camo', hash: 0x9DDBCF8C, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Digital Camo', hash: 0xB319A52C, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Digital Camo', hash: 0xC6836E12, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Digital Camo', hash: 0x43B1B173, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Patriotic', hash: 0x4ABDA3FA, weaponHashes: ['weapon_pistol_mk2'] },
    { name: 'Default Clip', hash: 0x45A3B6BB, weaponHashes: ['weapon_vintagepistol'] },
    { name: 'Extended Clip', hash: 0x33BA12E8, weaponHashes: ['weapon_vintagepistol'] },
    { name: 'Festive tint', hash: 0xD7DBF707, weaponHashes: ['weapon_raypistol'] },
    { name: 'Default Clip', hash: 0x54D41361, weaponHashes: ['weapon_ceramicpistol'] },
    { name: 'Extended Clip', hash: 0x81786CA9, weaponHashes: ['weapon_ceramicpistol'] },
    { name: 'Suppressor', hash: 0x9307D6FA, weaponHashes: ['weapon_ceramicpistol'] },
    { name: 'Default Clip', hash: 0xCB48AEF0, weaponHashes: ['weapon_microsmg'] },
    { name: 'Extended Clip', hash: 0x10E6BA2B, weaponHashes: ['weapon_microsmg'] },
    { name: 'Scope', hash: 0x9D2FBF29, weaponHashes: ['weapon_microsmg', 'weapon_assaultsmg', 'weapon_assaultrifle'] },
    { name: 'Yusuf Amir Luxury Finish', hash: 0x487AAE09, weaponHashes: ['weapon_microsmg'] },
    { name: 'Default Clip', hash: 0x26574997, weaponHashes: ['weapon_smg'] },
    { name: 'Extended Clip', hash: 0x350966FB, weaponHashes: ['weapon_smg'] },
    { name: 'Drum Magazine', hash: 0x79C77076, weaponHashes: ['weapon_smg'] },
    { name: 'Flashlight', hash: 0x7BC4CDDC, weaponHashes: ['weapon_smg', 'weapon_assaultsmg', 'weapon_combatpdw', 'weapon_pumpshotgun', 'weapon_assaultshotgun', 'weapon_bullpupshotgun', 'weapon_pumpshotgun_mk2', 'weapon_heavyshotgun', 'weapon_combatshotgun', 'weapon_assaultrifle', 'weapon_carbinerifle', 'weapon_advancedrifle', 'weapon_specialcarbine', 'weapon_bullpuprifle', 'weapon_bullpuprifle_mk2', 'weapon_specialcarbine_mk2', 'weapon_assaultrifle_mk2', 'weapon_carbinerifle_mk2', 'weapon_militaryrifle', 'weapon_marksmanrifle_mk2', 'weapon_marksmanrifle', 'weapon_grenadelauncher'] },
    { name: 'Scope', hash: 0x3CC6BA57, weaponHashes: ['weapon_smg'] },
    { name: 'Yusuf Amir Luxury Finish', hash: 0x27872C90, weaponHashes: ['weapon_smg'] },
    { name: 'Default Clip', hash: 0x8D1307B0, weaponHashes: ['weapon_assaultsmg'] },
    { name: 'Extended Clip', hash: 0xBB46E417, weaponHashes: ['weapon_assaultsmg'] },
    { name: 'Yusuf Amir Luxury Finish', hash: 0x278C78AF, weaponHashes: ['weapon_assaultsmg'] },
    { name: 'Default Clip', hash: 0x84C8B2D3, weaponHashes: ['weapon_minismg'] },
    { name: 'Extended Clip', hash: 0x937ED0B7, weaponHashes: ['weapon_minismg'] },
    { name: 'Default Clip', hash: 0x4C24806E, weaponHashes: ['weapon_smg_mk2'] },
    { name: 'Extended Clip', hash: 0xB9835B2E, weaponHashes: ['weapon_smg_mk2'] },
    { name: 'Tracer Rounds', hash: 0x7FEA36EC, weaponHashes: ['weapon_smg_mk2'] },
    { name: 'Incendiary Rounds', hash: 0xD99222E5, weaponHashes: ['weapon_smg_mk2'] },
    { name: 'Hollow Point Rounds', hash: 0x3A1BD6FA, weaponHashes: ['weapon_smg_mk2'] },
    { name: 'Full Metal Jacket Rounds', hash: 0xB5A715F, weaponHashes: ['weapon_smg_mk2'] },
    { name: 'Holographic Sight', hash: 0x9FDB5652, weaponHashes: ['weapon_smg_mk2'] },
    { name: 'Small Scope', hash: 0xE502AB6B, weaponHashes: ['weapon_smg_mk2'] },
    { name: 'Medium Scope', hash: 0x3DECC7DA, weaponHashes: ['weapon_smg_mk2'] },
    { name: 'Flat Muzzle Brake', hash: 0xB99402D4, weaponHashes: ['weapon_smg_mk2', 'weapon_bullpuprifle_mk2', 'weapon_specialcarbine_mk2', 'weapon_assaultrifle_mk2', 'weapon_carbinerifle_mk2', 'weapon_combatmg_mk2', 'weapon_marksmanrifle_mk2'] },
    { name: 'Tactical Muzzle Brake', hash: 0xC867A07B, weaponHashes: ['weapon_smg_mk2', 'weapon_bullpuprifle_mk2', 'weapon_specialcarbine_mk2', 'weapon_assaultrifle_mk2', 'weapon_carbinerifle_mk2', 'weapon_combatmg_mk2', 'weapon_marksmanrifle_mk2'] },
    { name: 'Fat-End Muzzle Brake', hash: 0xDE11CBCF, weaponHashes: ['weapon_smg_mk2', 'weapon_bullpuprifle_mk2', 'weapon_specialcarbine_mk2', 'weapon_assaultrifle_mk2', 'weapon_carbinerifle_mk2', 'weapon_combatmg_mk2', 'weapon_marksmanrifle_mk2'] },
    { name: 'Precision Muzzle Brake', hash: 0xEC9068CC, weaponHashes: ['weapon_smg_mk2', 'weapon_bullpuprifle_mk2', 'weapon_specialcarbine_mk2', 'weapon_assaultrifle_mk2', 'weapon_carbinerifle_mk2', 'weapon_combatmg_mk2', 'weapon_marksmanrifle_mk2'] },
    { name: 'Heavy Duty Muzzle Brake', hash: 0x2E7957A, weaponHashes: ['weapon_smg_mk2', 'weapon_bullpuprifle_mk2', 'weapon_specialcarbine_mk2', 'weapon_assaultrifle_mk2', 'weapon_carbinerifle_mk2', 'weapon_combatmg_mk2', 'weapon_marksmanrifle_mk2'] },
    { name: 'Slanted Muzzle Brake', hash: 0x347EF8AC, weaponHashes: ['weapon_smg_mk2', 'weapon_bullpuprifle_mk2', 'weapon_specialcarbine_mk2', 'weapon_assaultrifle_mk2', 'weapon_carbinerifle_mk2', 'weapon_combatmg_mk2', 'weapon_marksmanrifle_mk2'] },
    { name: 'Split-End Muzzle Brake', hash: 0x4DB62ABE, weaponHashes: ['weapon_smg_mk2', 'weapon_bullpuprifle_mk2', 'weapon_specialcarbine_mk2', 'weapon_assaultrifle_mk2', 'weapon_carbinerifle_mk2', 'weapon_combatmg_mk2', 'weapon_marksmanrifle_mk2'] },
    { name: 'Default Barrel', hash: 0xD9103EE1, weaponHashes: ['weapon_smg_mk2'] },
    { name: 'Heavy Barrel', hash: 0xA564D78B, weaponHashes: ['weapon_smg_mk2'] },
    { name: 'Digital Camo', hash: 0xC4979067, weaponHashes: ['weapon_smg_mk2'] },
    { name: 'Brushstroke Camo', hash: 0x3815A945, weaponHashes: ['weapon_smg_mk2'] },
    { name: 'Woodland Camo', hash: 0x4B4B4FB0, weaponHashes: ['weapon_smg_mk2'] },
    { name: 'Skull', hash: 0xEC729200, weaponHashes: ['weapon_smg_mk2'] },
    { name: 'Sessanta Nove', hash: 0x48F64B22, weaponHashes: ['weapon_smg_mk2'] },
    { name: 'Perseus', hash: 0x35992468, weaponHashes: ['weapon_smg_mk2'] },
    { name: 'Leopard', hash: 0x24B782A5, weaponHashes: ['weapon_smg_mk2'] },
    { name: 'Zebra', hash: 0xA2E67F01, weaponHashes: ['weapon_smg_mk2'] },
    { name: 'Geometric', hash: 0x2218FD68, weaponHashes: ['weapon_smg_mk2'] },
    { name: 'Boom!', hash: 0x45C5C3C5, weaponHashes: ['weapon_smg_mk2'] },
    { name: 'Patriotic', hash: 0x399D558F, weaponHashes: ['weapon_smg_mk2'] },
    { name: 'Default Clip', hash: 0x476E85FF, weaponHashes: ['weapon_machinepistol'] },
    { name: 'Extended Clip', hash: 0xB92C6979, weaponHashes: ['weapon_machinepistol'] },
    { name: 'Drum Magazine', hash: 0xA9E9CAF4, weaponHashes: ['weapon_machinepistol'] },
    { name: 'Default Clip', hash: 0x4317F19E, weaponHashes: ['weapon_combatpdw'] },
    { name: 'Extended Clip', hash: 0x334A5203, weaponHashes: ['weapon_combatpdw'] },
    { name: 'Drum Magazine', hash: 0x6EB8C8DB, weaponHashes: ['weapon_combatpdw'] },
    { name: 'Grip', hash: 0xC164F53, weaponHashes: ['weapon_combatpdw', 'weapon_assaultshotgun', 'weapon_bullpupshotgun', 'weapon_assaultrifle', 'weapon_carbinerifle', 'weapon_specialcarbine', 'weapon_bullpuprifle', 'weapon_combatmg', 'weapon_marksmanrifle', 'weapon_grenadelauncher', 'weapon_heavyshotgun'] },
    { name: 'Scope', hash: 0xAA2C45B4, weaponHashes: ['weapon_combatpdw', 'weapon_advancedrifle', 'weapon_bullpuprifle', 'weapon_militaryrifle', 'weapon_grenadelauncher'] },
    { name: 'Suppressor', hash: 0xE608B35E, weaponHashes: ['weapon_pumpshotgun'] },
    { name: 'Yusuf Amir Luxury Finish', hash: 0xA2D79DDB, weaponHashes: ['weapon_pumpshotgun'] },
    { name: 'Gilded Gun Metal Finish', hash: 0x85A64DF9, weaponHashes: ['weapon_sawnoffshotgun'] },
    { name: 'Default Clip', hash: 0x94E81BC7, weaponHashes: ['weapon_assaultshotgun'] },
    { name: 'Extended Clip', hash: 0x86BD7F72, weaponHashes: ['weapon_assaultshotgun'] },
    { name: 'Suppressor', hash: 0x837445AA, weaponHashes: ['weapon_assaultshotgun', 'weapon_carbinerifle', 'weapon_advancedrifle', 'weapon_bullpuprifle', 'weapon_bullpuprifle_mk2', 'weapon_carbinerifle_mk2', 'weapon_militaryrifle', 'weapon_combatshotgun', 'weapon_marksmanrifle_mk2', 'weapon_marksmanrifle'] },
    { name: 'Default Shells', hash: 0xCD940141, weaponHashes: ['weapon_pumpshotgun_mk2'] },
    { name: 'Dragon\'s Breath Shells', hash: 0x9F8A1BF5, weaponHashes: ['weapon_pumpshotgun_mk2'] },
    { name: 'Steel Buckshot Shells', hash: 0x4E65B425, weaponHashes: ['weapon_pumpshotgun_mk2'] },
    { name: 'Flechette Shells', hash: 0xE9582927, weaponHashes: ['weapon_pumpshotgun_mk2'] },
    { name: 'Explosive Slugs', hash: 0x3BE4465D, weaponHashes: ['weapon_pumpshotgun_mk2'] },
    { name: 'Medium Scope', hash: 0x3F3C8181, weaponHashes: ['weapon_pumpshotgun_mk2', 'weapon_bullpuprifle_mk2', 'weapon_combatmg_mk2'] },
    { name: 'Suppressor', hash: 0xAC42DF71, weaponHashes: ['weapon_pumpshotgun_mk2', 'weapon_heavysniper_mk2'] },
    { name: 'Squared Muzzle Brake', hash: 0x5F7DCE4D, weaponHashes: ['weapon_pumpshotgun_mk2', 'weapon_heavysniper_mk2'] },
    { name: 'Digital Camo', hash: 0xE3BD9E44, weaponHashes: ['weapon_pumpshotgun_mk2'] },
    { name: 'Brushstroke Camo', hash: 0x17148F9B, weaponHashes: ['weapon_pumpshotgun_mk2'] },
    { name: 'Woodland Camo', hash: 0x24D22B16, weaponHashes: ['weapon_pumpshotgun_mk2'] },
    { name: 'Skull', hash: 0xF2BEC6F0, weaponHashes: ['weapon_pumpshotgun_mk2'] },
    { name: 'Sessanta Nove', hash: 0x85627D, weaponHashes: ['weapon_pumpshotgun_mk2'] },
    { name: 'Perseus', hash: 0xDC2919C5, weaponHashes: ['weapon_pumpshotgun_mk2'] },
    { name: 'Leopard', hash: 0xE184247B, weaponHashes: ['weapon_pumpshotgun_mk2'] },
    { name: 'Zebra', hash: 0xD8EF9356, weaponHashes: ['weapon_pumpshotgun_mk2'] },
    { name: 'Geometric', hash: 0xEF29BFCA, weaponHashes: ['weapon_pumpshotgun_mk2'] },
    { name: 'Boom!', hash: 0x67AEB165, weaponHashes: ['weapon_pumpshotgun_mk2'] },
    { name: 'Patriotic', hash: 0x46411A1D, weaponHashes: ['weapon_pumpshotgun_mk2'] },
    { name: 'Default Clip', hash: 0x324F2D5F, weaponHashes: ['weapon_heavyshotgun'] },
    { name: 'Extended Clip', hash: 0x971CF6FD, weaponHashes: ['weapon_heavyshotgun'] },
    { name: 'Drum Magazine', hash: 0x88C7DA53, weaponHashes: ['weapon_heavyshotgun'] },
    { name: 'Default Clip', hash: 0xBE5EEA16, weaponHashes: ['weapon_assaultrifle'] },
    { name: 'Extended Clip', hash: 0xB1214F9B, weaponHashes: ['weapon_assaultrifle'] },
    { name: 'Drum Magazine', hash: 0xDBF0A53D, weaponHashes: ['weapon_assaultrifle'] },
    { name: 'Yusuf Amir Luxury Finish', hash: 0x4EAD7533, weaponHashes: ['weapon_assaultrifle'] },
    { name: 'Default Clip', hash: 0x9FBE33EC, weaponHashes: ['weapon_carbinerifle'] },
    { name: 'Extended Clip', hash: 0x91109691, weaponHashes: ['weapon_carbinerifle'] },
    { name: 'Box Magazine', hash: 0xBA62E935, weaponHashes: ['weapon_carbinerifle'] },
    { name: 'Scope', hash: 0xA0D89C42, weaponHashes: ['weapon_carbinerifle', 'weapon_specialcarbine', 'weapon_combatmg'] },
    { name: 'Yusuf Amir Luxury Finish', hash: 0xD89B9658, weaponHashes: ['weapon_carbinerifle'] },
    { name: 'Default Clip', hash: 0xFA8FA10F, weaponHashes: ['weapon_advancedrifle'] },
    { name: 'Extended Clip', hash: 0x8EC1C979, weaponHashes: ['weapon_advancedrifle'] },
    { name: 'Gilded Gun Metal Finish', hash: 0x377CD377, weaponHashes: ['weapon_advancedrifle'] },
    { name: 'Default Clip', hash: 0xC6C7E581, weaponHashes: ['weapon_specialcarbine'] },
    { name: 'Extended Clip', hash: 0x7C8BD10E, weaponHashes: ['weapon_specialcarbine'] },
    { name: 'Drum Magazine', hash: 0x6B59AEAA, weaponHashes: ['weapon_specialcarbine'] },
    { name: 'Etched Gun Metal Finish', hash: 0x730154F2, weaponHashes: ['weapon_specialcarbine'] },
    { name: 'Default Clip', hash: 0xC5A12F80, weaponHashes: ['weapon_bullpuprifle'] },
    { name: 'Extended Clip', hash: 0xB3688B0F, weaponHashes: ['weapon_bullpuprifle'] },
    { name: 'Gilded Gun Metal Finish', hash: 0xA857BC78, weaponHashes: ['weapon_bullpuprifle'] },
    { name: 'Default Clip', hash: 0x18929DA, weaponHashes: ['weapon_bullpuprifle_mk2'] },
    { name: 'Extended Clip', hash: 0xEFB00628, weaponHashes: ['weapon_bullpuprifle_mk2'] },
    { name: 'Tracer Rounds', hash: 0x822060A9, weaponHashes: ['weapon_bullpuprifle_mk2'] },
    { name: 'Incendiary Rounds', hash: 0xA99CF95A, weaponHashes: ['weapon_bullpuprifle_mk2'] },
    { name: 'Armor Piercing Rounds', hash: 0xFAA7F5ED, weaponHashes: ['weapon_bullpuprifle_mk2'] },
    { name: 'Full Metal Jacket Rounds', hash: 0x43621710, weaponHashes: ['weapon_bullpuprifle_mk2'] },
    { name: 'Small Scope', hash: 0xC7ADD105, weaponHashes: ['weapon_bullpuprifle_mk2'] },
    { name: 'Default Barrel', hash: 0x659AC11B, weaponHashes: ['weapon_bullpuprifle_mk2'] },
    { name: 'Heavy Barrel', hash: 0x3BF26DC7, weaponHashes: ['weapon_bullpuprifle_mk2'] },
    { name: 'Grip', hash: 0x9D65907A, weaponHashes: ['weapon_bullpuprifle_mk2', 'weapon_specialcarbine_mk2', 'weapon_assaultrifle_mk2', 'weapon_carbinerifle_mk2', 'weapon_combatmg_mk2', 'weapon_marksmanrifle_mk2'] },
    { name: 'Digital Camo', hash: 0xAE4055B7, weaponHashes: ['weapon_bullpuprifle_mk2'] },
    { name: 'Brushstroke Camo', hash: 0xB905ED6B, weaponHashes: ['weapon_bullpuprifle_mk2'] },
    { name: 'Woodland Camo', hash: 0xA6C448E8, weaponHashes: ['weapon_bullpuprifle_mk2'] },
    { name: 'Skull', hash: 0x9486246C, weaponHashes: ['weapon_bullpuprifle_mk2'] },
    { name: 'Sessanta Nove', hash: 0x8A390FD2, weaponHashes: ['weapon_bullpuprifle_mk2'] },
    { name: 'Perseus', hash: 0x2337FC5, weaponHashes: ['weapon_bullpuprifle_mk2'] },
    { name: 'Leopard', hash: 0xEFFFDB5E, weaponHashes: ['weapon_bullpuprifle_mk2'] },
    { name: 'Zebra', hash: 0xDDBDB6DA, weaponHashes: ['weapon_bullpuprifle_mk2'] },
    { name: 'Geometric', hash: 0xCB631225, weaponHashes: ['weapon_bullpuprifle_mk2'] },
    { name: 'Boom!', hash: 0xA87D541E, weaponHashes: ['weapon_bullpuprifle_mk2'] },
    { name: 'Patriotic', hash: 0xC5E9AE52, weaponHashes: ['weapon_bullpuprifle_mk2'] },
    { name: 'Default Clip', hash: 0x16C69281, weaponHashes: ['weapon_specialcarbine_mk2'] },
    { name: 'Extended Clip', hash: 0xDE1FA12C, weaponHashes: ['weapon_specialcarbine_mk2'] },
    { name: 'Tracer Rounds', hash: 0x8765C68A, weaponHashes: ['weapon_specialcarbine_mk2'] },
    { name: 'Incendiary Rounds', hash: 0xDE011286, weaponHashes: ['weapon_specialcarbine_mk2'] },
    { name: 'Armor Piercing Rounds', hash: 0x51351635, weaponHashes: ['weapon_specialcarbine_mk2'] },
    { name: 'Full Metal Jacket Rounds', hash: 0x503DEA90, weaponHashes: ['weapon_specialcarbine_mk2'] },
    { name: 'Large Scope', hash: 0xC66B6542, weaponHashes: ['weapon_specialcarbine_mk2', 'weapon_assaultrifle_mk2', 'weapon_carbinerifle_mk2', 'weapon_combatmg_mk2'] },
    { name: 'Default Barrel', hash: 0xE73653A9, weaponHashes: ['weapon_specialcarbine_mk2'] },
    { name: 'Heavy Barrel', hash: 0xF97F783B, weaponHashes: ['weapon_specialcarbine_mk2'] },
    { name: 'Digital Camo', hash: 0xD40BB53B, weaponHashes: ['weapon_specialcarbine_mk2'] },
    { name: 'Brushstroke Camo', hash: 0x431B238B, weaponHashes: ['weapon_specialcarbine_mk2'] },
    { name: 'Woodland Camo', hash: 0x34CF86F4, weaponHashes: ['weapon_specialcarbine_mk2'] },
    { name: 'Skull', hash: 0xB4C306DD, weaponHashes: ['weapon_specialcarbine_mk2'] },
    { name: 'Sessanta Nove', hash: 0xEE677A25, weaponHashes: ['weapon_specialcarbine_mk2'] },
    { name: 'Perseus', hash: 0xDF90DC78, weaponHashes: ['weapon_specialcarbine_mk2'] },
    { name: 'Leopard', hash: 0xA4C31EE, weaponHashes: ['weapon_specialcarbine_mk2'] },
    { name: 'Zebra', hash: 0x89CFB0F7, weaponHashes: ['weapon_specialcarbine_mk2'] },
    { name: 'Geometric', hash: 0x7B82145C, weaponHashes: ['weapon_specialcarbine_mk2'] },
    { name: 'Boom!', hash: 0x899CAF75, weaponHashes: ['weapon_specialcarbine_mk2'] },
    { name: 'Patriotic', hash: 0x5218C819, weaponHashes: ['weapon_specialcarbine_mk2'] },
    { name: 'Default Clip', hash: 0x8610343F, weaponHashes: ['weapon_assaultrifle_mk2'] },
    { name: 'Extended Clip', hash: 0xD12ACA6F, weaponHashes: ['weapon_assaultrifle_mk2'] },
    { name: 'Tracer Rounds', hash: 0xEF2C78C1, weaponHashes: ['weapon_assaultrifle_mk2'] },
    { name: 'Incendiary Rounds', hash: 0xFB70D853, weaponHashes: ['weapon_assaultrifle_mk2'] },
    { name: 'Armor Piercing Rounds', hash: 0xA7DD1E58, weaponHashes: ['weapon_assaultrifle_mk2'] },
    { name: 'Full Metal Jacket Rounds', hash: 0x63E0A098, weaponHashes: ['weapon_assaultrifle_mk2'] },
    { name: 'Default Barrel', hash: 0x43A49D26, weaponHashes: ['weapon_assaultrifle_mk2'] },
    { name: 'Heavy Barrel', hash: 0x5646C26A, weaponHashes: ['weapon_assaultrifle_mk2'] },
    { name: 'Digital Camo', hash: 0x911B24AF, weaponHashes: ['weapon_assaultrifle_mk2'] },
    { name: 'Brushstroke Camo', hash: 0x37E5444B, weaponHashes: ['weapon_assaultrifle_mk2'] },
    { name: 'Woodland Camo', hash: 0x538B7B97, weaponHashes: ['weapon_assaultrifle_mk2'] },
    { name: 'Skull', hash: 0x25789F72, weaponHashes: ['weapon_assaultrifle_mk2'] },
    { name: 'Sessanta Nove', hash: 0xC5495F2D, weaponHashes: ['weapon_assaultrifle_mk2'] },
    { name: 'Perseus', hash: 0xCF8B73B1, weaponHashes: ['weapon_assaultrifle_mk2'] },
    { name: 'Leopard', hash: 0xA9BB2811, weaponHashes: ['weapon_assaultrifle_mk2'] },
    { name: 'Zebra', hash: 0xFC674D54, weaponHashes: ['weapon_assaultrifle_mk2'] },
    { name: 'Geometric', hash: 0x7C7FCD9B, weaponHashes: ['weapon_assaultrifle_mk2'] },
    { name: 'Boom!', hash: 0xA5C38392, weaponHashes: ['weapon_assaultrifle_mk2'] },
    { name: 'Patriotic', hash: 0xB9B15DB0, weaponHashes: ['weapon_assaultrifle_mk2'] },
    { name: 'Default Clip', hash: 0x4C7A391E, weaponHashes: ['weapon_carbinerifle_mk2'] },
    { name: 'Extended Clip', hash: 0x5DD5DBD5, weaponHashes: ['weapon_carbinerifle_mk2'] },
    { name: 'Tracer Rounds', hash: 0x1757F566, weaponHashes: ['weapon_carbinerifle_mk2'] },
    { name: 'Incendiary Rounds', hash: 0x3D25C2A7, weaponHashes: ['weapon_carbinerifle_mk2'] },
    { name: 'Armor Piercing Rounds', hash: 0x255D5D57, weaponHashes: ['weapon_carbinerifle_mk2'] },
    { name: 'Full Metal Jacket Rounds', hash: 0x44032F11, weaponHashes: ['weapon_carbinerifle_mk2'] },
    { name: 'Default Barrel', hash: 0x833637FF, weaponHashes: ['weapon_carbinerifle_mk2'] },
    { name: 'Heavy Barrel', hash: 0x8B3C480B, weaponHashes: ['weapon_carbinerifle_mk2'] },
    { name: 'Digital Camo', hash: 0x4BDD6F16, weaponHashes: ['weapon_carbinerifle_mk2'] },
    { name: 'Brushstroke Camo', hash: 0x406A7908, weaponHashes: ['weapon_carbinerifle_mk2'] },
    { name: 'Woodland Camo', hash: 0x2F3856A4, weaponHashes: ['weapon_carbinerifle_mk2'] },
    { name: 'Skull', hash: 0xE50C424D, weaponHashes: ['weapon_carbinerifle_mk2'] },
    { name: 'Sessanta Nove', hash: 0xD37D1F2F, weaponHashes: ['weapon_carbinerifle_mk2'] },
    { name: 'Perseus', hash: 0x86268483, weaponHashes: ['weapon_carbinerifle_mk2'] },
    { name: 'Leopard', hash: 0xF420E076, weaponHashes: ['weapon_carbinerifle_mk2'] },
    { name: 'Zebra', hash: 0xAAE14DF8, weaponHashes: ['weapon_carbinerifle_mk2'] },
    { name: 'Geometric', hash: 0x9893A95D, weaponHashes: ['weapon_carbinerifle_mk2'] },
    { name: 'Boom!', hash: 0x6B13CD3E, weaponHashes: ['weapon_carbinerifle_mk2'] },
    { name: 'Patriotic', hash: 0xDA55CD3F, weaponHashes: ['weapon_carbinerifle_mk2'] },
    { name: 'Default Clip', hash: 0x513F0A63, weaponHashes: ['weapon_compactrifle'] },
    { name: 'Extended Clip', hash: 0x59FF9BF8, weaponHashes: ['weapon_compactrifle'] },
    { name: 'Drum Magazine', hash: 0xC607740E, weaponHashes: ['weapon_compactrifle'] },
    { name: 'Default Clip', hash: 0x2D46D83B, weaponHashes: ['weapon_militaryrifle'] },
    { name: 'Extended Clip', hash: 0x684ACE42, weaponHashes: ['weapon_militaryrifle'] },
    { name: 'Iron Sights', hash: 0x6B82F395, weaponHashes: ['weapon_militaryrifle'] },
    { name: 'Default Clip', hash: 0xF434EF84, weaponHashes: ['weapon_mg'] },
    { name: 'Extended Clip', hash: 0x82158B47, weaponHashes: ['weapon_mg'] },
    { name: 'Scope', hash: 0x3C00AFED, weaponHashes: ['weapon_mg'] },
    { name: 'Yusuf Amir Luxury Finish', hash: 0xD6DABABE, weaponHashes: ['weapon_mg'] },
    { name: 'Default Clip', hash: 0xE1FFB34A, weaponHashes: ['weapon_combatmg'] },
    { name: 'Extended Clip', hash: 0xD6C59CD6, weaponHashes: ['weapon_combatmg'] },
    { name: 'Etched Gun Metal Finish', hash: 0x92FECCDD, weaponHashes: ['weapon_combatmg'] },
    { name: 'Default Clip', hash: 0x492B257C, weaponHashes: ['weapon_combatmg_mk2'] },
    { name: 'Extended Clip', hash: 0x17DF42E9, weaponHashes: ['weapon_combatmg_mk2'] },
    { name: 'Tracer Rounds', hash: 0xF6649745, weaponHashes: ['weapon_combatmg_mk2'] },
    { name: 'Incendiary Rounds', hash: 0xC326BDBA, weaponHashes: ['weapon_combatmg_mk2'] },
    { name: 'Armor Piercing Rounds', hash: 0x29882423, weaponHashes: ['weapon_combatmg_mk2'] },
    { name: 'Full Metal Jacket Rounds', hash: 0x57EF1CC8, weaponHashes: ['weapon_combatmg_mk2'] },
    { name: 'Default Barrel', hash: 0xC34EF234, weaponHashes: ['weapon_combatmg_mk2'] },
    { name: 'Heavy Barrel', hash: 0xB5E2575B, weaponHashes: ['weapon_combatmg_mk2'] },
    { name: 'Digital Camo', hash: 0x4A768CB5, weaponHashes: ['weapon_combatmg_mk2'] },
    { name: 'Brushstroke Camo', hash: 0xCCE06BBD, weaponHashes: ['weapon_combatmg_mk2'] },
    { name: 'Woodland Camo', hash: 0xBE94CF26, weaponHashes: ['weapon_combatmg_mk2'] },
    { name: 'Skull', hash: 0x7609BE11, weaponHashes: ['weapon_combatmg_mk2'] },
    { name: 'Sessanta Nove', hash: 0x48AF6351, weaponHashes: ['weapon_combatmg_mk2'] },
    { name: 'Perseus', hash: 0x9186750A, weaponHashes: ['weapon_combatmg_mk2'] },
    { name: 'Leopard', hash: 0x84555AA8, weaponHashes: ['weapon_combatmg_mk2'] },
    { name: 'Zebra', hash: 0x1B4C088B, weaponHashes: ['weapon_combatmg_mk2'] },
    { name: 'Geometric', hash: 0xE046DFC, weaponHashes: ['weapon_combatmg_mk2'] },
    { name: 'Boom!', hash: 0x28B536E, weaponHashes: ['weapon_combatmg_mk2'] },
    { name: 'Patriotic', hash: 0xD703C94D, weaponHashes: ['weapon_combatmg_mk2'] },
    { name: 'Default Clip', hash: 0x1CE5A6A5, weaponHashes: ['weapon_gusenberg'] },
    { name: 'Extended Clip', hash: 0xEAC8C270, weaponHashes: ['weapon_gusenberg'] },
    { name: 'Default Clip', hash: 0x9BC64089, weaponHashes: ['weapon_sniperrifle'] },
    { name: 'Scope', hash: 0xD2443DDC, weaponHashes: ['weapon_sniperrifle', 'weapon_heavysniper'] },
    { name: 'Advanced Scope', hash: 0xBC54DA77, weaponHashes: ['weapon_sniperrifle', 'weapon_heavysniper', 'weapon_heavysniper_mk2'] },
    { name: 'Etched Wood Grip Finish', hash: 0x4032B5E7, weaponHashes: ['weapon_sniperrifle'] },
    { name: 'Default Clip', hash: 0x476F52F4, weaponHashes: ['weapon_heavysniper'] },
    { name: 'Default Clip', hash: 0x94E12DCE, weaponHashes: ['weapon_marksmanrifle_mk2'] },
    { name: 'Extended Clip', hash: 0xE6CFD1AA, weaponHashes: ['weapon_marksmanrifle_mk2'] },
    { name: 'Tracer Rounds', hash: 0xD77A22D2, weaponHashes: ['weapon_marksmanrifle_mk2'] },
    { name: 'Incendiary Rounds', hash: 0x6DD7A86E, weaponHashes: ['weapon_marksmanrifle_mk2'] },
    { name: 'Armor Piercing Rounds', hash: 0xF46FD079, weaponHashes: ['weapon_marksmanrifle_mk2'] },
    { name: 'Full Metal Jacket Rounds', hash: 0xE14A9ED3, weaponHashes: ['weapon_marksmanrifle_mk2'] },
    { name: 'Zoom Scope', hash: 0x5B1C713C, weaponHashes: ['weapon_marksmanrifle_mk2'] },
    { name: 'Default Barrel', hash: 0x381B5D89, weaponHashes: ['weapon_marksmanrifle_mk2'] },
    { name: 'Heavy Barrel', hash: 0x68373DDC, weaponHashes: ['weapon_marksmanrifle_mk2'] },
    { name: 'Digital Camo', hash: 0x9094FBA0, weaponHashes: ['weapon_marksmanrifle_mk2'] },
    { name: 'Brushstroke Camo', hash: 0x7320F4B2, weaponHashes: ['weapon_marksmanrifle_mk2'] },
    { name: 'Woodland Camo', hash: 0x60CF500F, weaponHashes: ['weapon_marksmanrifle_mk2'] },
    { name: 'Skull', hash: 0xFE668B3F, weaponHashes: ['weapon_marksmanrifle_mk2'] },
    { name: 'Sessanta Nove', hash: 0xF3757559, weaponHashes: ['weapon_marksmanrifle_mk2'] },
    { name: 'Perseus', hash: 0x193B40E8, weaponHashes: ['weapon_marksmanrifle_mk2'] },
    { name: 'Leopard', hash: 0x107D2F6C, weaponHashes: ['weapon_marksmanrifle_mk2'] },
    { name: 'Zebra', hash: 0xC4E91841, weaponHashes: ['weapon_marksmanrifle_mk2'] },
    { name: 'Geometric', hash: 0x9BB1C5D3, weaponHashes: ['weapon_marksmanrifle_mk2'] },
    { name: 'Boom!', hash: 0x3B61040B, weaponHashes: ['weapon_marksmanrifle_mk2'] },
    { name: 'Boom!', hash: 0xB7A316DA, weaponHashes: ['weapon_marksmanrifle_mk2'] },
    { name: 'Default Clip', hash: 0xFA1E1A28, weaponHashes: ['weapon_heavysniper_mk2'] },
    { name: 'Extended Clip', hash: 0x2CD8FF9D, weaponHashes: ['weapon_heavysniper_mk2'] },
    { name: 'Incendiary Rounds', hash: 0xEC0F617, weaponHashes: ['weapon_heavysniper_mk2'] },
    { name: 'Armor Piercing Rounds', hash: 0xF835D6D4, weaponHashes: ['weapon_heavysniper_mk2'] },
    { name: 'Full Metal Jacket Rounds', hash: 0x3BE948F6, weaponHashes: ['weapon_heavysniper_mk2'] },
    { name: 'Explosive Rounds', hash: 0x89EBDAA7, weaponHashes: ['weapon_heavysniper_mk2'] },
    { name: 'Zoom Scope', hash: 0x82C10383, weaponHashes: ['weapon_heavysniper_mk2'] },
    { name: 'Night Vision Scope', hash: 0xB68010B0, weaponHashes: ['weapon_heavysniper_mk2'] },
    { name: 'Thermal Scope', hash: 0x2E43DA41, weaponHashes: ['weapon_heavysniper_mk2'] },
    { name: 'Bell-End Muzzle Brake', hash: 0x6927E1A1, weaponHashes: ['weapon_heavysniper_mk2'] },
    { name: 'Default Barrel', hash: 0x909630B7, weaponHashes: ['weapon_heavysniper_mk2'] },
    { name: 'Heavy Barrel', hash: 0x108AB09E, weaponHashes: ['weapon_heavysniper_mk2'] },
    { name: 'Digital Camo', hash: 0xF8337D02, weaponHashes: ['weapon_heavysniper_mk2'] },
    { name: 'Brushstroke Camo', hash: 0xC5BEDD65, weaponHashes: ['weapon_heavysniper_mk2'] },
    { name: 'Woodland Camo', hash: 0xE9712475, weaponHashes: ['weapon_heavysniper_mk2'] },
    { name: 'Skull', hash: 0x13AA78E7, weaponHashes: ['weapon_heavysniper_mk2'] },
    { name: 'Sessanta Nove', hash: 0x26591E50, weaponHashes: ['weapon_heavysniper_mk2'] },
    { name: 'Perseus', hash: 0x302731EC, weaponHashes: ['weapon_heavysniper_mk2'] },
    { name: 'Leopard', hash: 0xAC722A78, weaponHashes: ['weapon_heavysniper_mk2'] },
    { name: 'Zebra', hash: 0xBEA4CEDD, weaponHashes: ['weapon_heavysniper_mk2'] },
    { name: 'Geometric', hash: 0xCD776C82, weaponHashes: ['weapon_heavysniper_mk2'] },
    { name: 'Boom!', hash: 0xABC5ACC7, weaponHashes: ['weapon_heavysniper_mk2'] },
    { name: 'Patriotic', hash: 0x6C32D2EB, weaponHashes: ['weapon_heavysniper_mk2'] },
    { name: 'Default Clip', hash: 0xD83B4141, weaponHashes: ['weapon_marksmanrifle'] },
    { name: 'Extended Clip', hash: 0xCCFD2AC5, weaponHashes: ['weapon_marksmanrifle'] },
    { name: 'Scope', hash: 0x1C221B1A, weaponHashes: ['weapon_marksmanrifle'] },
    { name: 'Yusuf Amir Luxury Finish', hash: 0x161E9241, weaponHashes: ['weapon_marksmanrifle'] },
    { name: 'Default Clip', hash: 0x11AE5C97, weaponHashes: ['weapon_grenadelauncher'] },
];

// Weapon tint indices
export const WEAPON_TINTS = [
    { id: 0, name: 'Default' },
    { id: 1, name: 'Green' },
    { id: 2, name: 'Gold' },
    { id: 3, name: 'Pink' },
    { id: 4, name: 'Army' },
    { id: 5, name: 'LSPD' },
    { id: 6, name: 'Orange' },
    { id: 7, name: 'Platinum' },
];
